use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        notifications, preferences, quick_pane, recording, recording_overlay, recovery,
        transcription,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        recording::get_default_recording_shortcut,
        recording::update_recording_shortcut,
        recording::start_recording,
        recording::stop_recording,
        recording::check_microphone_permission,
        recording::request_microphone_permission,
        recording_overlay::show_recording_overlay,
        recording_overlay::report_recording_overlay_rendered,
        recording_overlay::dismiss_recording_overlay,
        recording_overlay::toggle_recording_overlay,
        recording_overlay::cancel_recording,
        recording_overlay::open_microphone_settings,
        transcription::check_model_status,
        transcription::get_model_directory,
        transcription::open_model_directory,
        transcription::cancel_transcription,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
